export const categories = [
  'All',
  'Poultry Feeds',
  'Chicks',
  'Ducklings',
  'Eggs',
  'Pig Feeds',
  'Cattle Feeds',
  'Supplements',
  'Feeders & Drinkers',
];

const products = [
  {
    id: 1,
    name: 'Premium Sonali Finisher',
    category: 'Poultry Feeds',
    price: '₹1,900',
    originalPrice: '₹2,000',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/HP_sonali_starter.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },

  {
    id: 2,
    name: 'Pre-Starter Feed',
    category: 'Poultry Feeds',
    price: '₹2,700',
    originalPrice: '₹2,800',
    description: 'Calcium-rich feed for laying hens',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/HP_PreStarter.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.9,
    benefits: ['High calcium', 'Better egg production', 'Shell strength'],
    ingredients: 'Corn, Calcium carbonate, Protein meal, Vitamins',
    packaging: '25kg, 50kg bags',
    inStock: true,
  },
  {
    id: 3,
    name: 'Samrat Premium Finisher',
    category: 'Poultry Feeds',
    price: '₹2,650',
    originalPrice: '₹2,700',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Samrat_BF.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 4,
    name: 'HenPro Broiler Finisher',
    category: 'Poultry Feeds',
    price: '₹2,650',
    originalPrice: '₹2,700',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/HP_BroilerFinisher.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 5,
    name: 'Magic Finisher',
    category: 'Poultry Feeds',
    price: '₹2,750',
    originalPrice: null,
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/MagicFinisher.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 6,
    name: 'Desi Finisher',
    category: 'Poultry Feeds',
    price: '₹1,900',
    originalPrice: '₹2,000',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Desi_Finisher.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },

  {
    id: 7,
    name: 'NutriTech Broiler Finisher',
    category: 'Poultry Feeds',
    price: '₹2,650',
    originalPrice: '₹2,700',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/NutriTech_BF.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 8,
    name: 'Cosmic Finisher',
    category: 'Poultry Feeds',
    price: '₹2,650',
    originalPrice: '₹2,700',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/cosmic.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 9,
    name: 'Samrat Cattle Feed(Dana)',
    category: 'Cattle Feeds',
    price: '₹1,400',
    originalPrice: '₹1,500',
    description: 'High-protein feed for rapid growth',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Samrat_CattleFeed.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 10,
    name: 'Maha Pig Feed',
    category: 'Pig Feeds',
    price: '₹1,400',
    originalPrice: null,
    description: 'Balanced nutrition for pigs',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Maha_PigFeed.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.5,
    benefits: ['Balanced nutrition', 'Fast weight gain', 'Cost effective'],
    ingredients: 'Corn, Barley, Protein concentrate, Minerals',
    packaging: '50kg bags',
    inStock: false,
  },
  {
    id: 11,
    name: 'Samrat Pig Feed',
    category: 'Pig Feeds',
    price: '₹1,500',
    originalPrice: null,
    description: 'Balanced nutrition for pigs',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Samrat_PigFeed.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.5,
    benefits: ['Balanced nutrition', 'Fast weight gain', 'Cost effective'],
    ingredients: 'Corn, Barley, Protein concentrate, Minerals',
    packaging: '50kg bags',
    inStock: false,
  },
  {
    id: 12,
    name: 'Healthy Day-Old Chicks(Broiler)',
    category: 'Chicks',
    price: '₹55',
    originalPrice: '₹60',
    description: 'Vaccinated healthy chicks',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Broiler.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.7,
    benefits: ['Vaccinated', 'Healthy breed', 'High survival rate'],
    ingredients: 'Broiler breed, Rhode Island Red',
    packaging: 'Minimum 10 pieces',
    inStock: true,
  },
  {
    id: 13,
    name: 'Healthy Day-Old Chicks(Layer)',
    category: 'Chicks',
    price: '₹55',
    originalPrice: '₹60',
    description: 'Vaccinated healthy chicks',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Layer.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.7,
    benefits: ['Vaccinated', 'Healthy breed', 'High survival rate'],
    ingredients: 'Broiler breed, Rhode Island Red',
    packaging: 'Minimum 10 pieces',
    inStock: true,
  },
  {
    id: 14,
    name: 'Healthy Old-Day Ducklings',
    category: 'Ducklings',
    price: '₹120',
    originalPrice: null,
    description: 'Vaccinated Healthy ducklings',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Ducklings.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.6,
    benefits: ['Water-resistant pellets', 'Easy digestion', 'Growth formula'],
    ingredients: 'Fish meal, Corn, Rice bran, Vitamins',
    packaging: '25kg bags',
    inStock: true,
  },
  {
    id: 15,
    name: 'Farm Fresh Eggs',
    category: 'Eggs',
    price: '₹190',
    originalPrice: '₹200',
    description: 'Free-range chicken eggs',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Eggs.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.9,
    benefits: ['Free-range', 'High protein', 'Fresh daily'],
    ingredients: 'Natural farm eggs',
    packaging: '30 pieces per tray',
    inStock: true,
  },

  {
    id: 16,
    name: 'Biospark-V 1 Litre',
    category: 'Supplements',
    price: '₹220',
    originalPrice: '₹223',
    description: 'Supplement enriched with amino acids and essential minerals',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Biospark_1ltr.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.7,
    benefits: [
      'Better growth',
      'Better egg production',
      'Improves Feed Conversion Ratio (FCR) and overall bird vitality',
    ],
    ingredients:
      'Protein Hydrolysate, Arginine, Leucine, Lysine, Methionine, Valine',
    packaging: '1L bottles',
    inStock: true,
  },
  {
    id: 17,
    name: 'Biospark-V 5 Litre',
    category: 'Supplements',
    price: '₹350',
    originalPrice: '₹400',
    description: 'Essential B-vitamins for poultry health',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Biospark_5ltr.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.7,
    benefits: [
      'Better growth',
      'Better egg production',
      'Improves Feed Conversion Ratio (FCR) and overall bird vitality',
    ],
    ingredients:
      'Protein Hydrolysate, Arginine, Leucine, Lysine, Methionine, Valine',
    packaging: '5L Jars',
    inStock: true,
  },
  {
    id: 18,
    name: 'Calfos-Vet',
    category: 'Supplements',
    price: '₹280',
    originalPrice: null,
    description:
      'Calcium supplement with phosporus, Vit D3, Vit B12 & Carbohydrates',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Calfosvet.jpg?${Date.now()}',
    stock: 'Fresh Today',
    rating: 4.6,
    benefits: ['Stronger bones', 'Better shell quality', 'Prevents deficiency'],
    ingredients: 'Calcium carbonate, Vitamin D3, Magnesium',
    packaging: '500g containers',
    inStock: true,
  },
  {
    id: 19,
    name: 'Grow Gold',
    category: 'Supplements',
    price: '₹450',
    originalPrice: '₹500',
    description: 'Growth Promoter & Performance Enhancer',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/GrowGold.jpg??${Date.now()}',
    stock: 'In Stock',
    rating: 4.8,
    benefits: ['Better digestion', 'Immune support', 'Growth enhancement'],
    ingredients: 'Lactobacillus, Bifidobacterium, Enzymes, Prebiotics',
    packaging: '250g sachets',
    inStock: true,
  },
  {
    id: 20,
    name: 'Toxiliv',
    category: 'Supplements',
    price: '₹450',
    originalPrice: null,
    description: 'Digestive health supplement',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Toxiliv.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.8,
    benefits: ['Boost Liver Function', 'Enhance Metabolism', 'Enhance Growth'],
    ingredients: 'Lactobacillus, Bifidobacterium, Enzymes, Prebiotics',
    packaging: '500ml bottles',
    inStock: true,
  },
  {
    id: 21,
    name: 'Feeder',
    category: 'Feeders & Drinkers',
    price: '₹450',
    originalPrice: null,
    description:
      'Durable and easy-to-clean chick feeder. Available in multiple sizes.',
    image:
      'https://res.cloudinary.com/dzpwirstm/image/upload/Feeder.jpg?${Date.now()}',
    stock: 'In Stock',
    rating: 4.8,
    benefits: [
      'Promotes hygienic feeding environment',
      'Reduces feed spillage and contamination',
      'Supports uniform growth by ensuring consistent feed access',
    ],
    ingredients: 'Not Applicable',
    packaging: '1Ltr,  2Ltr, 5Ltr',
    inStock: true,
  },
  {
    id: 22,
    name: 'Drinker',
    category: 'Feeders & Drinkers',
    price: '₹250',
    originalPrice: '₹350',
    description:
      'Sturdy chick drinker with anti-spill design. Available in various sizes for easy hydration management.',
    image: 'https://res.cloudinary.com/dzpwirstm/image/upload/Drinker.jpg',
    stock: 'In Stock',
    rating: 4.8,
    benefits: [
      'Ensures clean and accessible drinking water',
      'Prevents waterborne infections',
      'Encourages healthy hydration for better digestion and immunity',
    ],
    ingredients: 'Not Applicable',
    packaging: '1Ltr,  2Ltr, 5Ltr',
    inStock: true,
  },
];

export default products;
