export const categories = [
  'All',
  'Poultry Feeds',
  'Chicks',
  'Ducklings',
  'Eggs',
  'Pig Feeds',
  'Cattle Feeds',
  'Supplements',
];

export const products = [
  {
    id: 1,
    name: 'Premium Sonali Finisher',
    category: 'Poultry Feeds',
    price: '₹1,900',
    originalPrice: '₹2,000',
    description: 'High-protein feed for rapid growth',
    image:
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 11,
    name: 'Samrat Premium Finisher',
    category: 'Poultry Feeds',
    price: '₹2,650',
    originalPrice: '₹2,700',
    description: 'High-protein feed for rapid growth',
    image:
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
  {
    id: 2,
    name: 'Pre-Starter Feed',
    category: 'Poultry Feeds',
    price: '₹2,700',
    originalPrice: '₹2,800',
    description: 'Calcium-rich feed for laying hens',
    image:
      'https://images.unsplash.com/photo-1571414329451-9cb3d7b77880?w=400&h=300&fit=crop',
    stock: 'In Stock',
    rating: 4.9,
    benefits: ['High calcium', 'Better egg production', 'Shell strength'],
    ingredients: 'Corn, Calcium carbonate, Protein meal, Vitamins',
    packaging: '25kg, 50kg bags',
    inStock: true,
  },
  {
    id: 3,
    name: 'Healthy Day-Old Chicks(Broiler)',
    category: 'Chicks',
    price: '₹55',
    originalPrice: '₹60',
    description: 'Vaccinated healthy chicks',
    image:
      'https://images.unsplash.com/photo-1546272989-40c92939c6c2?q=80&w=982&auto=format&fit=crop',
    stock: 'Fresh Today',
    rating: 4.7,
    benefits: ['Vaccinated', 'Healthy breed', 'High survival rate'],
    ingredients: 'Broiler breed, Rhode Island Red',
    packaging: 'Minimum 10 pieces',
    inStock: true,
  },
  {
    id: 3,
    name: 'Healthy Day-Old Chicks(Layer)',
    category: 'Chicks',
    price: '₹55',
    originalPrice: '₹60',
    description: 'Vaccinated healthy chicks',
    image:
      'https://images.unsplash.com/photo-1546833629-86e5534d5496?q=80&w=1170&auto=format&fit=crop',
    stock: 'Fresh Today',
    rating: 4.7,
    benefits: ['Vaccinated', 'Healthy breed', 'High survival rate'],
    ingredients: 'Broiler breed, Rhode Island Red',
    packaging: 'Minimum 10 pieces',
    inStock: true,
  },
  {
    id: 4,
    name: 'Healthy Old-Day Ducklings',
    category: 'Ducklings',
    price: '₹120',
    originalPrice: null,
    description: 'Vaccinated Healthy ducklings',
    image:
      'https://images.unsplash.com/photo-1442689859438-97407280183f?q=80&w=1170&auto=format&fit=crop',
    stock: 'In Stock',
    rating: 4.6,
    benefits: ['Water-resistant pellets', 'Easy digestion', 'Growth formula'],
    ingredients: 'Fish meal, Corn, Rice bran, Vitamins',
    packaging: '25kg bags',
    inStock: true,
  },
  {
    id: 5,
    name: 'Farm Fresh Eggs',
    category: 'Eggs',
    price: '₹120',
    originalPrice: null,
    description: 'Free-range chicken eggs',
    image:
      'https://images.unsplash.com/photo-1498654077810-12c21d4d6dc3?q=80&w=1170&auto=format&fit=crop',
    stock: 'Fresh Today',
    rating: 4.9,
    benefits: ['Free-range', 'High protein', 'Fresh daily'],
    ingredients: 'Natural farm eggs',
    packaging: '30 pieces per tray',
    inStock: true,
  },
  {
    id: 6,
    name: 'Pig Grower Feed',
    category: 'Pig Feeds',
    price: '₹1,900',
    originalPrice: null,
    description: 'Balanced nutrition for pigs',
    image:
      'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400&h=300&fit=crop',
    stock: 'In Stock',
    rating: 4.5,
    benefits: ['Balanced nutrition', 'Fast weight gain', 'Cost effective'],
    ingredients: 'Corn, Barley, Protein concentrate, Minerals',
    packaging: '50kg bags',
    inStock: false,
  },
  {
    id: 7,
    name: 'Vitamin B-Complex',
    category: 'Supplements',
    price: '₹350',
    originalPrice: '₹400',
    description: 'Essential B-vitamins for poultry health',
    image:
      'https://images.unsplash.com/photo-1584362917165-526a968579e8?w=400&h=300&fit=crop',
    stock: 'In Stock',
    rating: 4.7,
    benefits: ['Boosts immunity', 'Better egg production', 'Stress reduction'],
    ingredients: 'Vitamin B1, B2, B6, B12, Folic acid, Biotin',
    packaging: '100ml bottles',
    inStock: true,
  },
  {
    id: 8,
    name: 'Calcium + D3 Supplement',
    category: 'Supplements',
    price: '₹280',
    originalPrice: null,
    description: 'Calcium supplement with Vitamin D3',
    image:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
    stock: 'Fresh Today',
    rating: 4.6,
    benefits: ['Stronger bones', 'Better shell quality', 'Prevents deficiency'],
    ingredients: 'Calcium carbonate, Vitamin D3, Magnesium',
    packaging: '500g containers',
    inStock: true,
  },
  {
    id: 9,
    name: 'Probiotics Plus',
    category: 'Supplements',
    price: '₹450',
    originalPrice: null,
    description: 'Digestive health supplement',
    image:
      'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop',
    stock: 'In Stock',
    rating: 4.8,
    benefits: ['Better digestion', 'Immune support', 'Growth enhancement'],
    ingredients: 'Lactobacillus, Bifidobacterium, Enzymes, Prebiotics',
    packaging: '250g sachets',
    inStock: true,
  },
  {
    id: 10,
    name: 'Boiler Starter Feed',
    category: 'Poultry Feeds',
    price: '₹1,900',
    originalPrice: '₹2,000',
    description: 'High-protein feed for rapid growth',
    image:
      'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop',
    stock: 'Fresh Today',
    rating: 4.8,
    benefits: ['High protein content', 'Vitamin enriched', 'Fast growth'],
    ingredients: 'Corn, Soybean meal, Wheat, Vitamins A, D, E',
    packaging: '50kg bags',
    inStock: true,
  },
];
